### ISSUE TITLE
Sound.cpp won't compile

### ISSUE THREAD

**Issue by Gskartwii** [Myzilla-Web-Resources/OpenBlox#2]
I'm getting the following output from `make all`:

	make[1]: Entering directory '/home/gskw/src/OpenBlox'
	g++ -c -m64 -pipe -g -std=c++0x -Wall -W -D_REENTRANT -fPIE -DGXX_EXPERIMENTAL_CXX0X -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Idebug -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o debug/Sound.o src/ob_instance/Sound.cpp
	src/ob_instance/Sound.cpp:127:59: error: ‘FMOD_CHANNEL_CALLBACKTYPE’ has not been declared
	  FMOD_RESULT F_CALLBACK snd_callback(FMOD_CHANNEL* fchan, FMOD_CHANNEL_CALLBACKTYPE type, void *commanddata1, void *commanddata2){
		                                                   ^
	src/ob_instance/Sound.cpp: In function ‘FMOD_RESULT ob_instance::snd_callback(FMOD_CHANNEL*, int, void*, void*)’:
	src/ob_instance/Sound.cpp:139:15: error: ‘FMOD_CHANNEL_CALLBACKTYPE_END’ was not declared in this scope
	    if(type == FMOD_CHANNEL_CALLBACKTYPE_END){
		       ^
	src/ob_instance/Sound.cpp: In member function ‘void ob_instance::Sound::Play()’:
	src/ob_instance/Sound.cpp:173:59: error: invalid conversion from ‘FMOD_RESULT (*)(FMOD_CHANNEL*, int, void*, void*)’ to ‘FMOD_CHANNELCONTROL_CALLBACK {aka FMOD_RESULT (*)(FMOD_CHANNELCONTROL*, FMOD_CHANNELCONTROL_TYPE, FMOD_CHANNELCONTROL_CALLBACK_TYPE, void*, void*)}’ [-fpermissive]
	      result = FMOD_Channel_SetCallback(fchan, snd_callback);
		                                                   ^
	In file included from src/ob_instance/Sound.cpp:6:0:
	/usr/local/include/fmod.h:305:19: note: initializing argument 2 of ‘FMOD_RESULT FMOD_Channel_SetCallback(FMOD_CHANNEL*, FMOD_CHANNELCONTROL_CALLBACK)’
	 FMOD_RESULT F_API FMOD_Channel_SetCallback              (FMOD_CHANNEL *channel, FMOD_CHANNELCONTROL_CALLBACK callback);
		           ^
	src/ob_instance/Sound.cpp: In member function ‘void ob_instance::Sound::hitEnd()’:
	src/ob_instance/Sound.cpp:240:58: error: invalid conversion from ‘FMOD_RESULT (*)(FMOD_CHANNEL*, int, void*, void*)’ to ‘FMOD_CHANNELCONTROL_CALLBACK {aka FMOD_RESULT (*)(FMOD_CHANNELCONTROL*, FMOD_CHANNELCONTROL_TYPE, FMOD_CHANNELCONTROL_CALLBACK_TYPE, void*, void*)}’ [-fpermissive]
	     result = FMOD_Channel_SetCallback(fchan, snd_callback);
		                                                  ^
	In file included from src/ob_instance/Sound.cpp:6:0:
	/usr/local/include/fmod.h:305:19: note: initializing argument 2 of ‘FMOD_RESULT FMOD_Channel_SetCallback(FMOD_CHANNEL*, FMOD_CHANNELCONTROL_CALLBACK)’
	 FMOD_RESULT F_API FMOD_Channel_SetCallback              (FMOD_CHANNEL *channel, FMOD_CHANNELCONTROL_CALLBACK callback);
		           ^
	QtMakefile.Debug:4847: recipe for target 'debug/Sound.o' failed
	make[1]: *** [debug/Sound.o] Error 1
	make[1]: Leaving directory '/home/gskw/src/OpenBlox'
	QtMakefile:38: recipe for target 'debug' failed
	make: *** [debug] Error 2

I'm guessing it's a version mismatch. I'm using the newest version which I downloaded from the site today (8.4.2015)

**Comment by JohnMHarrisJr** [comment]
Do you mean FMOD version?

**Comment by DigiTechs** [comment]
Are you sure you have the dependencies set up correctly? We're using FMOD Ex 4.44.52 (which JohnMH thinks we're not but the header files clearly say) but it isn't documented correctly.

**Comment by JohnMHarrisJr** [comment]
We're using FMOD Ex 4.44.52. Here's the version of FMOD Ex we're using for the Travis CI build script: http://www.myzillawr.com/ob_linux_dep/fmodapi44452linux.tar.gz

The includes go straight into /usr/include (or other include directory) and not /usr/include/fmod as some third party documetation shows.

**Comment by Gskartwii** [comment]
I'm using FMOD 1.05.15, but will download that. Thanks!
